### ISSUE TITLE
forgot SetStateOnHurt

### ISSUE THREAD

**Issue by TheTimeSweeper** [OminousArchitect/KamunagiRedux#1]
https://github.com/OminousArchitect/KamunagiRedux/blob/049a0b34199ac36206bcb8764f7a70a9a4571ada/Data/Bodies/Kamunagi/Kamunagi.cs#L218

when you add new EntityStateMachines they have to be added to the SetStateOnHurt component which handles stunning and freezing you

**Comment by OminousArchitect** [comment]
Fixed! Thank you!
