### ISSUE TITLE
Issue #0

### ISSUE THREAD

**Issue by OminousArchitect** [OminousArchitect/KamunagiRedux#2]
![axiom](https://github.com/user-attachments/assets/3fd1d72a-7fdf-439a-b7c3-ad284979dfa3)
![earth](https://github.com/user-attachments/assets/2cd6d29d-b304-4cb6-beb9-2b5bbfdb5338)
![fire](https://github.com/user-attachments/assets/8814be69-d192-4c5b-b8fb-3e6b0781fc27)
![flashbang](https://github.com/user-attachments/assets/ea708ea6-0c8a-4ef7-bf6e-98d4f9e7f8b0)
![frost](https://github.com/user-attachments/assets/7d16ad41-5151-44fb-9aa2-e75fed4d4f59)
![jinsoku](https://github.com/user-attachments/assets/04ed9011-04c2-416f-bd0a-ba12bb01ee32)
![kuko](https://github.com/user-attachments/assets/c15eb809-be03-4bcd-99ab-40855653b2b2)
![laser](https://github.com/user-attachments/assets/326536e9-1657-48b3-91b9-7d2c29dc0374)
![lightning](https://github.com/user-attachments/assets/fcd65f1e-b7a3-4fbc-b4ea-5cea9619307b)
![mantle](https://github.com/user-attachments/assets/c91b4c1b-52a3-472e-8d06-43e3f8362e73)
![mothmoth](https://github.com/user-attachments/assets/0db0ca76-1021-4868-a4a2-f66e69bf5ced)
![orb](https://github.com/user-attachments/assets/079ae4f5-21ea-4299-8c98-7eaa7b0db1c5)
![prayer](https://github.com/user-attachments/assets/3a75afea-2893-44ab-8eb2-05a0e4c48f66)
![sealing](https://github.com/user-attachments/assets/99faae5e-5d87-4e64-9d9b-50b6c0bc4fb8)
![seed](https://github.com/user-attachments/assets/a40c41a2-5945-4d5f-8972-d3278aa8543a)
![shadowflame](https://github.com/user-attachments/assets/7ef76ca6-ab31-466b-a209-bc3ce8457e76)
![spirit](https://github.com/user-attachments/assets/f75eefde-2e16-4f56-91b3-e9c2003188d2)
![star](https://github.com/user-attachments/assets/98bff5c7-cb16-4d7c-8625-53366ee57bf2)
![tatari](https://github.com/user-attachments/assets/542ef5e7-86f1-4bb5-991f-5fe7674389c6)
![veil](https://github.com/user-attachments/assets/bcb96350-25d0-4094-9b40-2d5c5e33c7a6)
![water](https://github.com/user-attachments/assets/3145dd35-0812-462f-a2e6-0e9f590a30f5)
![winds](https://github.com/user-attachments/assets/02b1acbf-0a74-4f35-aa32-d0a2bbed2838)
![windstrikes](https://github.com/user-attachments/assets/ee195883-b0b7-4055-8846-16f2f19f4b06)
![woshis](https://github.com/user-attachments/assets/823cb23c-2434-422f-b7c3-71bbb630f890)
issues

**Comment by OminousArchitect** [comment]
![prayer](https://github.com/user-attachments/assets/6a30afb3-6e46-487b-b16d-d85f634484e0)

**Comment by OminousArchitect** [comment]
![atuyGod](https://github.com/user-attachments/assets/e97f4447-47d0-43dc-9439-711cce3b4e32)

**Comment by Bubbet** [comment]
How are these issues

**Comment by OminousArchitect** [comment]
Image hosting

**Comment by OminousArchitect** [comment]
![passive1](https://github.com/user-attachments/assets/cfa4ad0f-359b-4c1e-aaf4-8ba01c74e94b)

**Comment by OminousArchitect** [comment]
![passive0](https://github.com/user-attachments/assets/3db50524-1890-4d21-8f78-e013c433fbd5)

**Comment by OminousArchitect** [comment]
![kit1](https://github.com/user-attachments/assets/525427ec-3f5f-4b82-918f-0e58776dacbb)

![kit2](https://github.com/user-attachments/assets/9a071f47-672f-4143-becb-3fde12fab23f)

**Comment by OminousArchitect** [comment]
![kit3](https://github.com/user-attachments/assets/218463d9-aa55-4d7a-9457-8f1c43820e29)

**Comment by OminousArchitect** [comment]
![kit4](https://github.com/user-attachments/assets/717ca6e4-9e9b-4e93-ba99-e23f2abe0cb1)

**Comment by OminousArchitect** [comment]
![kit5](https://github.com/user-attachments/assets/8eca2527-83c6-4131-8709-56627818ce78)

**Comment by OminousArchitect** [comment]
![kit6](https://github.com/user-attachments/assets/75587ea8-265d-4da8-a949-31c3ea4cbc9b)
